### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abhimishra-dev**
Please consider the updated DRC-20, Doginals index as well that is provided by the DPal wallet who provided the first inscription wallet services in DRC-20 doginals back in early last year. In the updated DRC-20 index it has handled the issues with security vulnerability, Sybil attack, witch nodes and double spending that were not taken care during initial DRC-20 Doginals index. Public GitHub for the updated DRC-20, Doginals index as below 👇

https://github.com/dogexme/dogim-indexer

Please note that $dogim has killed the witch nodes of $dogi inscription/token from DRC-20, doginals.

### CODE REVIEW

**Comment by lianqing123** [comment]
dogim to the moon！！！

**Comment by HJustinH** [comment]
We are Dogim army

**Comment by 1024blackke** [comment]
dogim to the moon

**Comment by yhai943** [comment]
Dogim: Pawsitively Secure, Inclusively Fair! 🐾 OKX Web3 Wallet, Let's Launch Dogim with Equity and Excitement! 🚀 #DogimSupport #OKXFairLaunch

**Comment by Jenkinty** [comment]
Dogim to the moon

**Comment by abhimishra-dev** [comment]
@yanminmin @debuggor , could you please check this pull request where we have an updated index for DRC-20, doginals. This index should be included as well for the wider DRC-20 community.

**Comment by HJustinH** [comment]
​#Drc20 #Dogim
​1. The world's first inscription swap ecology
​2.$dogim (Multi-gold dog) is the doge chain dragon head inscription
​3. Currently only 3 million market value, value depression, huge potential!
​4. Real holding address 13000
​5. 1.2 billion big dogs were traded
​6. "uniswap" for dog chains
​https://t.me/dogim center
​Gold dog is gold enough to get next year's race gold!

**Pull request closed without merging**
